version: '3.8'
services:
  traefik:
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  fastapi:
    image: sharabhs/fastapiserver:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.centralus.cloudapp.azure.com`) && (PathPrefix(`/timenow`))"
  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`fastapi.centralus.cloudapp.azure.com`) && (PathPrefix(`/whoami`))"