name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/sharabhshukla/fastapi-traefik-server/fastapiserver:$(date +%s)
    - name: push image to github repository
      run: docker push docker.pkg.github.com/sharabhshukla/fastapi-traefik-server/fastapiserver:$(date +%s)
